const informasiLayananList = [
  {
    kategori: "fasilitas-umum",
    slug: "pendidikan",
    title: "Pendidikan",
    desc: "Akses pendidikan dasar hingga menengah yang tersedia di desa.",
    image: "/assets/informasi/pendidikan.jpg",
    children: [
      {
        slug: "sd-negeri",
        title: "SD Negeri",
        desc: "Sekolah Dasar Negeri Desa Guwo memberikan pendidikan berkualitas gratis.",
        image: "/assets/informasi/sd.jpg",
        content: "SD Negeri di Desa Guwo memiliki tenaga pendidik berkompeten dan fasilitas memadai.",
      },
      {
        slug: "smp-terdekat",
        title: "SMP Terdekat",
        desc: "SMP terdekat dapat dijangkau dengan mudah oleh warga desa.",
        image: "/assets/informasi/smp.jpg",
        content: "SMP Terdekat menawarkan kurikulum yang mendukung perkembangan potensi siswa.",
      },
    ],
  },
  {
    kategori: "fasilitas-umum",
    slug: "kesehatan",
    title: "Kesehatan",
    desc: "Layanan kesehatan untuk warga desa.",
    image: "/assets/informasi/kesehatan.jpg",
    children: [
      {
        slug: "puskesmas-terdekat",
        title: "Puskesmas Terdekat",
        desc: "Puskesmas melayani pemeriksaan dan pengobatan gratis warga.",
        image: "/assets/informasi/puskesmas.jpg",
        content: "Puskesmas memiliki fasilitas dokter umum, dokter gigi, serta bidan desa.",
      },
      {
        slug: "posyandu",
        title: "Posyandu",
        desc: "Pelayanan kesehatan balita dan ibu hamil di Posyandu.",
        image: "/assets/informasi/posyandu.jpg",
        content: "Posyandu rutin digelar di balai desa setiap bulan.",
      },
    ],
  },
  {
    kategori: "fasilitas-umum",
    slug: "keagamaan",
    title: "Keagamaan",
    desc: "Sarana ibadah dan kegiatan keagamaan di desa.",
    image: "/assets/informasi/keagamaan.jpg",
    children: [
      {
        slug: "masjid-mushola",
        title: "Masjid / Mushola",
        desc: "Tempat ibadah umat muslim yang terawat dan nyaman.",
        image: "/assets/informasi/masjid.jpg",
        content: "Masjid dan mushola desa rutin digunakan untuk shalat berjamaah dan kegiatan pengajian.",
      },
      {
        slug: "kegiatan-keagamaan",
        title: "Kegiatan Keagamaan",
        desc: "Berbagai acara keagamaan di tingkat dusun dan desa.",
        image: "/assets/informasi/kegiatan-keagamaan.jpg",
        content: "Mulai dari pengajian, peringatan hari besar Islam, hingga santunan anak yatim.",
      },
    ],
  },
  {
    kategori: "layanan-balai-desa",
    slug: "administrasi-surat",
    title: "Administrasi Surat",
    desc: "Pengurusan berbagai surat di balai desa.",
    image: "/assets/informasi/administrasi.jpg",
    children: [
      {
        slug: "surat-domisili",
        title: "Surat Domisili",
        desc: "Surat keterangan tempat tinggal resmi warga.",
        image: "/assets/informasi/surat-domisili.jpg",
        content: "Diperlukan untuk berbagai keperluan administrasi dan kependudukan.",
      },
      {
        slug: "surat-keterangan-usaha",
        title: "Surat Keterangan Usaha",
        desc: "Membuktikan legalitas usaha warga.",
        image: "/assets/informasi/surat-usaha.jpg",
        content: "Menjadi syarat pengajuan izin atau bantuan usaha.",
      },
      {
        slug: "surat-tidak-mampu",
        title: "Surat Tidak Mampu",
        desc: "Diperuntukkan warga kurang mampu.",
        image: "/assets/informasi/surat-tidak-mampu.jpg",
        content: "Digunakan untuk pengajuan bantuan sosial atau beasiswa.",
      },
    ],
  },
  {
    kategori: "layanan-balai-desa",
    slug: "layanan-kependudukan",
    title: "Layanan Kependudukan",
    desc: "Pelayanan dokumen kependudukan warga.",
    image: "/assets/informasi/kependudukan.jpg",
    children: [
      {
        slug: "ktp",
        title: "Pelayanan KTP",
        desc: "Pembuatan dan perpanjangan KTP elektronik.",
        image: "/assets/informasi/ktp.jpg",
        content: "Warga dapat mengurus KTP baru atau perpanjangan dengan mudah di balai desa.",
      },
      {
        slug: "kk",
        title: "Pelayanan KK",
        desc: "Pengurusan kartu keluarga baru maupun perubahan data.",
        image: "/assets/informasi/kk.jpg",
        content: "KK diperlukan sebagai dokumen dasar kependudukan keluarga.",
      },
      {
        slug: "akta-kelahiran",
        title: "Akta Kelahiran",
        desc: "Pencatatan kelahiran anak warga desa.",
        image: "/assets/informasi/akta-kelahiran.jpg",
        content: "Pembuatan akta kelahiran mempermudah akses layanan publik ke depannya.",
      },
    ],
  },
  {
    kategori: "layanan-balai-desa",
    slug: "pengaduan-warga",
    title: "Pengaduan Warga",
    desc: "Sarana menyampaikan aspirasi atau keluhan.",
    image: "/assets/informasi/pengaduan.jpg",
    children: [
      {
        slug: "kontak-perangkat-desa",
        title: "Kontak Perangkat Desa",
        desc: "Hubungi perangkat desa terkait pengaduan.",
        image: "/assets/informasi/kontak.jpg",
        content: "Kontak perangkat desa tersedia melalui telepon maupun datang langsung ke kantor balai desa.",
      },
    ],
  },
  {
    kategori: "layanan-balai-desa",
    slug: "bantuan-sosial",
    title: "Bantuan Sosial",
    desc: "Bantuan sosial yang tersedia untuk warga.",
    image: "/assets/informasi/bansos.jpg",
    children: [
      {
        slug: "blt-dana-desa",
        title: "BLT Dana Desa",
        desc: "Bantuan langsung tunai dari dana desa.",
        image: "/assets/informasi/blt.jpg",
        content: "Diberikan kepada warga terdampak ekonomi sesuai kriteria penerima.",
      },
      {
        slug: "pkh",
        title: "PKH",
        desc: "Program Keluarga Harapan bagi warga kurang mampu.",
        image: "/assets/informasi/pkh.jpg",
        content: "PKH membantu pendidikan anak dan kesehatan ibu hamil di keluarga prasejahtera.",
      },
      {
        slug: "bantuan-pangan",
        title: "Bantuan Pangan",
        desc: "Distribusi pangan bagi warga miskin.",
        image: "/assets/informasi/bantuan-pangan.jpg",
        content: "Biasanya diberikan rutin per triwulan melalui balai desa.",
      },
    ],
  },
  {
    kategori: "potensi-umkm",
    slug: "umkm",
    title: "UMKM",
    desc: "Produk dan pelaku UMKM di desa.",
    image: "/assets/informasi/umkm.jpg",
    children: [
      {
        slug: "kerajinan-tangan",
        title: "Kerajinan Tangan",
        desc: "Produk kerajinan lokal khas desa.",
        image: "/assets/informasi/kerajinan.jpg",
        content: "Berbagai kerajinan berbahan alami yang dijual ke pasar luar desa.",
      },
      {
        slug: "daftar-umkm",
        title: "Daftar UMKM",
        desc: "Pelaku UMKM aktif di Desa Guwo.",
        image: "/assets/informasi/daftar-umkm.jpg",
        content: "Tercatat lebih dari 20 UMKM aktif yang difasilitasi oleh pemerintah desa.",
      },
    ],
  },
  {
    kategori: "potensi-umkm",
    slug: "pertanian",
    title: "Pertanian",
    desc: "Potensi hasil pertanian dan perkebunan desa.",
    image: "/assets/informasi/pertanian.jpg",
    children: [
      {
        slug: "jagung",
        title: "Jagung",
        desc: "Komoditas jagung sebagai sumber pangan.",
        image: "/assets/informasi/jagung.jpg",
        content: "Jagung menjadi salah satu hasil panen utama desa.",
      },
      {
        slug: "perkebunan-kopi",
        title: "Perkebunan Kopi",
        desc: "Kebun kopi rakyat di perbukitan desa.",
        image: "/assets/informasi/kopi.jpg",
        content: "Kopi Guwo terkenal memiliki cita rasa khas dan dijual ke berbagai daerah.",
      },
    ],
  },
];

export default informasiLayananList;
