// src/app/kabar/data.js
const kabarList = [
 {
  slug: "gotong-royong-lapangan-bak-sampah",
  title: "Gotong Royong Perbaikan Lapangan dan Pembuatan Bak Sampah di Dusun Jatiri",
  image: ["/assets/photos/membuat lapangan/WhatsApp Image 2025-06-29 at 22.10.41_087f2ded.jpg","/assets/photos/membuat lapangan/WhatsApp Image 2025-06-29 at 22.10.43_7c478556.jpg" ],
  images: "/assets/photos/membuat lapangan/WhatsApp Image 2025-06-29 at 22.10.42_4a490a4a.jpg",
  date: "29 Juni 2025",
  summary: "Mahasiswa KKNT Universitas Duta Bangsa Surakarta bersama warga Dusun Jatiri melakukan kerja bakti memperbaiki lapangan dan membangun bak sampah permanen untuk meningkatkan kebersihan dan fasilitas olahraga masyarakat.",
  content: "Mahasiswa Kuliah Kerja Nyata Tematik (KKNT) Universitas Duta Bangsa Surakarta bersama warga Dusun Jatiri bergotong royong pada hari Minggu, 29 Juni 2025, untuk memperbaiki lapangan yang sudah rusak dan membangun bak sampah permanen sebagai sarana kebersihan. Kegiatan ini bertujuan mengembalikan fungsi lapangan sebagai ruang publik yang sehat dan aman bagi aktivitas olahraga maupun kegiatan sosial warga. Sebelumnya, kondisi lapangan kurang terawat akibat hujan deras dan semak liar, sehingga memerlukan perbaikan menyeluruh.\n\nDalam proses gotong royong ini, mahasiswa dan warga membersihkan area lapangan, meratakan tanah, memperbaiki drainase, serta menyingkirkan rumput liar agar lapangan kembali layak digunakan. Sementara itu, pembangunan bak sampah dilakukan agar warga memiliki tempat pembuangan yang lebih tertib, mengurangi praktik membuang sampah sembarangan yang selama ini menjadi persoalan lingkungan. Mahasiswa KKNT juga turut memberikan edukasi singkat mengenai pentingnya memilah sampah organik dan anorganik.\n\nKegiatan ini menjadi salah satu wujud nyata semangat gotong royong di Dusun Jatiri. Melalui kolaborasi antara mahasiswa dan warga, fasilitas publik yang dulunya terbengkalai dapat difungsikan kembali dan dijaga bersama. Lapangan yang sudah diperbaiki diharapkan mampu menumbuhkan minat olahraga masyarakat, terutama anak-anak dan pemuda desa, sehingga tercipta gaya hidup sehat sekaligus mempererat hubungan antarwarga.\n\nKetua KKNT Universitas Duta Bangsa Surakarta menyampaikan bahwa kegiatan ini adalah langkah awal penting dalam membangun kesadaran warga tentang perilaku hidup bersih dan peduli lingkungan. Dengan terciptanya fasilitas bak sampah permanen, diharapkan warga semakin terbiasa menjaga kebersihan sekitar. Sementara lapangan yang sudah diperbaiki akan menjadi pusat aktivitas yang bermanfaat bagi seluruh warga Dusun Jatiri, menciptakan suasana desa yang lebih tertata, bersih, dan nyaman."
},
 {
  slug: "penyuluhan-kesehatan",
  title: "Penyuluhan dan Pemeriksaan Kesehatan oleh Mahasiswa KKNT UDB di Desa Guwo",
  image: ["/","/"],
  date: "21 Juni 2025",
  summary: "Mahasiswa KKNT Universitas Duta Bangsa Surakarta mengadakan penyuluhan kesehatan dan pemeriksaan gratis yang diikuti warga Desa Guwo untuk meningkatkan kesadaran akan pentingnya pencegahan penyakit hipertensi dan diabetes.",
  content: "Mahasiswa Kuliah Kerja Nyata Tematik (KKNT) Universitas Duta Bangsa Surakarta melaksanakan kegiatan penyuluhan dan pemeriksaan kesehatan gratis di Desa Guwo pada tanggal 21 Juni 2025. Acara ini diikuti antusias oleh seluruh warga desa yang hadir untuk memeriksakan kondisi kesehatan mereka sekaligus mendapatkan edukasi terkait pencegahan penyakit hipertensi dan diabetes melitus. Kegiatan ini merupakan salah satu program pengabdian mahasiswa KKNT dalam mendukung kesehatan masyarakat pedesaan.\n\nPemeriksaan kesehatan yang dilakukan meliputi pengecekan tekanan darah, pemeriksaan kadar gula darah, serta konsultasi langsung dengan tenaga kesehatan pendamping yang turut dilibatkan dalam kegiatan tersebut. Selain itu, mahasiswa KKNT juga menyampaikan materi penyuluhan tentang pola makan sehat, aktivitas fisik, serta cara menjaga gaya hidup agar terhindar dari risiko penyakit tidak menular.\n\nSeluruh warga Desa Guwo memberikan apresiasi tinggi atas kegiatan ini karena membantu mereka memahami kondisi kesehatannya secara lebih baik. Harapannya, hasil pemeriksaan ini dapat menjadi dasar warga untuk melakukan upaya pencegahan lebih lanjut dan memeriksakan diri secara rutin ke fasilitas kesehatan terdekat.\n\nMenurut Ketua KKNT Universitas Duta Bangsa Surakarta, kegiatan penyuluhan kesehatan ini diharapkan dapat menyadarkan masyarakat akan pentingnya menjaga kesehatan, terutama terkait risiko hipertensi dan diabetes melitus, sehingga kualitas hidup warga Desa Guwo ke depan semakin baik dan terhindar dari penyakit yang berbahaya."
}
,
 {
  slug: "workshop-bucket-pkk",
  title: "Workshop Pembuatan Bucket oleh Mahasiswa KKNT untuk Ibu-Ibu PKK Desa Guwo",
  image: ["/images/kabar3.jpg",""],
  date: "1 Juli 2025",
  summary: "Mahasiswa KKNT Universitas Duta Bangsa Surakarta mengadakan workshop pembuatan bucket untuk ibu-ibu PKK Desa Guwo sebagai upaya mengasah kreativitas dan peluang usaha online.",
  content: "Mahasiswa Kuliah Kerja Nyata Tematik (KKNT) Universitas Duta Bangsa Surakarta menyelenggarakan workshop pembuatan bucket bagi ibu-ibu PKK Desa Guwo pada tanggal 1 Juli 2025 di aula balai desa. Kegiatan ini bertujuan memberikan pelatihan keterampilan membuat bucket sederhana yang dapat dikembangkan menjadi produk bernilai jual, sekaligus meningkatkan kreativitas ibu-ibu dalam memanfaatkan bahan yang tersedia di lingkungan sekitar.\n\nPeserta workshop diajak mempraktikkan langsung cara menyusun, menghias, serta mengemas bucket agar menarik dan memiliki nilai jual lebih tinggi. Mahasiswa KKNT juga berbagi tips bagaimana memasarkan produk secara daring melalui platform media sosial maupun marketplace, sehingga membuka peluang usaha baru berbasis kreativitas rumah tangga.\n\nIbu-ibu PKK Desa Guwo menyambut kegiatan ini dengan sangat antusias, karena selain menambah keterampilan baru, mereka juga mendapatkan wawasan tentang peluang berjualan online yang semakin relevan di era digital. Dengan adanya workshop ini, diharapkan lahir ide-ide usaha yang dapat membantu meningkatkan perekonomian keluarga.\n\nMenurut mahasiswa KKNT Universitas Duta Bangsa Surakarta, kegiatan workshop ini diharapkan mampu membuka inovasi dan insight baru bagi para ibu-ibu PKK, serta mengasah kreativitas mereka untuk terus berkembang dalam menciptakan produk yang bernilai dan diminati pasar."
}

]

export default kabarList
